support adding and displaying dishes on BE
instrybutor/pasnik pull request #21
Opened 2021-09-29 11:03 UTC by Isterius

2021-09-29 20:06 UTC, pawelkondraciuk requested changes

2021-09-30 04:43 UTC, Isterius commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
for dish it is person who added it

2021-09-30 04:45 UTC, Isterius commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  paid: boolean;
how we can sum balance for user if we don't know if he paid for specific dish?

2021-09-30 04:46 UTC, Isterius commented on libs/api/data-transfer/src/lib/create-dish-body.model.ts
> +export interface CreateDishBody {
true, I wanted to remove one :D thx

2021-09-30 05:36 UTC, pawelkondraciuk commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
We could add dish owner to UserDish

2021-09-30 05:37 UTC, pawelkondraciuk commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  paid: boolean;
Do we need to know if he paid for that dish? We could just sum dish price and shipping and add it to user balance

2021-09-30 05:38 UTC, pawelkondraciuk commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
But I think there won't be any special powers for dish owner

2021-09-30 09:36 UTC, Isterius commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
for now it's only needed to show `delete`/`ediit` controls in dish row

2021-09-30 09:38 UTC, pawelkondraciuk commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
Can we use user related to the dish via UserDishEntity? There is already dishOwner field

2021-09-30 09:39 UTC, Isterius commented on apps/nestjs-api/src/app/entities/dish.entity.ts
> +  @OneToOne(() => UserEntity)
👀 🔍

2021-12-03 15:51 UTC, closed without merging